apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: ca-ops-referentiel
spec:
  serviceAccountName: knative-build
  source:
    git:
      url: https://source.developers.google.com/p/coding-archi-ops/r/ca-ops-referentiel
      revision: master
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.1.0
    args:
    - --dockerfile=/workspace/Dockerfile
    - --destination=gcr.io/ca-ops/ca-ops-referentiel